# Generated by Django 4.0.4 on 2023-01-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_geeksmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaCirlce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radius', models.IntegerField(max_length=200)),
                ('TotalArea', models.IntegerField(max_length=200)),
                ('OneCircleArea', models.IntegerField(max_length=200)),
                ('HitAllArea', models.IntegerField(max_length=200)),
                ('HitAllAreaPercentage', models.IntegerField(max_length=200)),
                ('HitOnceArea', models.IntegerField(max_length=200)),
                ('HitOnceAreaPercentage', models.IntegerField(max_length=200)),
                ('OverlapArea', models.IntegerField(max_length=200)),
                ('OverlapAreaPercentage', models.IntegerField(max_length=200)),
                ('UntouchedArea', models.IntegerField(max_length=200)),
                ('UntouchedAreaPercentage', models.IntegerField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='GeeksModel',
        ),
    ]
